logging:
  level: INFO
  loggers:
    com.company.applications: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9999

swagger:
  resourcePackage: com.company.applications.resources
  includeSwaggerResource: true